// Conteúdo do jogo: missões, itens e falas. Dinheiro em cobre (100 cobre = 1 prata, 100 prata = 1 ouro).

export const ITEMS = {
  pedra: { name: 'Lápide de Regresso', quality: 'common', icon: 'hearth', desc: 'Usar: Leva você de volta à Praça do Relógio Torto.', flavor: 'Tem seu nome gravado. Que reconfortante.', use: 'hearth' },
  biscoito: { name: 'Biscoito de Peixe Duvidoso', quality: 'common', icon: 'biscuit', desc: 'Usar: Restaura 12 de vida. Talvez.', flavor: 'Cheira a peixe. Ou a meia. Ou a peixe de meia.', use: 'eat' },
  chapeu: { name: 'Chapéu de Abóbora Oficial', quality: 'uncommon', icon: 'pumpkinhat', desc: 'Equipar: Sua cabeça fica 37% mais outonal.', flavor: 'Presente da Prefeitura. Não é comestível (tentaram).', use: 'hat' },
  rotula: { name: 'Rótula Sobressalente', quality: 'poor', icon: 'kneecap', desc: 'Não serve para nada.', flavor: 'Pertencia a alguém. Agora pertence a você.' },
  lanterna: { name: 'Lanterna de Vaga-lumes', quality: 'rare', icon: 'lantern', desc: 'Passivo: Sua lanterna brilha em verde mágico e ilumina o dobro.', flavor: 'Os vaga-lumes cobram hora extra.' },
  belzebu: { name: 'Belzebuzinho', quality: 'epic', icon: 'chick', desc: 'Mascote: Chama o filhote de avestruz demônio que acha que você é a mãe dele. Depois do mingau ardido, cospe fogo nos inimigos.', flavor: 'Não alimentar depois da meia-noite. Nem antes.', use: 'pet' },
  vassoura: { name: 'Vassoura Velha da Vesga', quality: 'epic', icon: 'broom', desc: 'Montaria: Aumenta a velocidade de movimento em 65%.', flavor: 'Voa baixinho e reclama o tempo todo.', use: 'mount' },
  colar: { name: 'Colar de Presas Falsas', quality: 'uncommon', icon: 'fangs', desc: '+5 de Charme Macabro.', flavor: 'O Conde tinha um par sobrando. De 1703.' },
  pena: { name: 'Pena de Corvo Ofendido', quality: 'common', icon: 'feather', desc: 'Material de artesanato.', flavor: 'Ainda está resmungando.' },
  carta: { name: 'Carta Perfumada', quality: 'quest', icon: 'letter', desc: 'Item de missão.', flavor: 'Cheira a lavanda e naftalina. Molhada de lágrimas de ectoplasma.' },
  resposta: { name: 'Bilhete da Lady Névoa', quality: 'quest', icon: 'letter2', desc: 'Item de missão.', flavor: 'Está escrito "SIM" com letra caprichada. E um borrão de batom.' },
  dentadura: { name: 'Dentadura de Ouro do Conde', quality: 'quest', icon: 'dentures', desc: 'Item de missão.', flavor: 'Ainda úmida de sapo. Eca.' },
  castanholas: { name: 'Castanholas de Costela', quality: 'common', icon: 'bone', desc: 'Não serve para nada, mas faz tac-tac.', flavor: 'Tumbalacatumba tumba tá, agora com ritmo.' },
  tonico: { name: 'Tônico Capilar da Vesga', quality: 'rare', icon: 'potion', desc: 'Usar: Restaura 40 de vida. Recarga de 60 s.', flavor: 'Efeito colateral: sobrancelha nova.', use: 'tonic' },
  capa: { name: 'Capa de Veludo Roída', quality: 'rare', icon: 'cape', desc: '+7 de Drama Noturno.', flavor: 'Os buracos são de traça. Ou de morcego. Ou do tataravô.' },
  buque: { name: 'Buquê da Lady Névoa', quality: 'epic', icon: 'bouquet', desc: 'Não murcha. Já veio murcho.', flavor: 'Quem pega o buquê é o próximo a morrer de amor.' },
};

export const QUALITY_COLORS = {
  poor: '#9a928c', common: '#efe6d2', uncommon: '#9ee05a', rare: '#5ab4ff', epic: '#c77dff', quest: '#ffa84a',
};

export const QUESTS = [
  {
    id: 'gato',
    title: 'Cadê o Sr. Bigodes?',
    level: 1,
    giver: 'aranhilda',
    turnIn: 'aranhilda',
    text:
      'Ai, ai, ai! Meu gatinho, o Sr. Bigodes, fugiu de novo!\n\nEle tem três olhos, um bigode torto e o hábito horrível de trazer ratos-zumbis para a cama. Da última vez que o vi, ele estava perseguindo uma mariposa rumo à Colina Espiral.\n\nTraga meu bebê de volta, querido, antes que ele assombre algum canário.',
    summary: 'Encontre o Sr. Bigodes perto da Colina Espiral e leve-o de volta para Dona Aranhilda.',
    objectives: [{ key: 'gato', need: 1, label: 'Sr. Bigodes resgatado' }],
    progress: 'Já achou meu bebê? Ele atende por "Sr. Bigodes", "Pestinha" ou pelo barulho de lata de sardinha abrindo.',
    complete: 'SR. BIGODES! Seu monstrinho peludo! Por onde andou?\n\n...Ele arranhou você? Que bom, significa que gostou de você. Tome, uma recompensa pela sua coragem. Asse com carinho.',
    rewards: { xp: 350, money: 3500, items: ['biscoito'] },
    area: 'gato',
  },
  {
    id: 'aboboras',
    title: 'Abóboras Fujonas',
    level: 1,
    giver: 'prefeito',
    turnIn: 'prefeito',
    text:
      'Cidadão! Uma crise sem precedentes assola nossa amada vila!\n\nAs abóboras do Festival da Colheita Macabra criaram pernas... bem, não pernas, mas criaram coragem... e fugiram para o Sítio do Seu Custódio!\n\nSem abóboras não há festival, e sem festival eu não sou reeleito. Capture as fujonas. Elas pulam bastante, mas não são muito espertas.',
    summary: 'Capture 5 Abóboras Fujonas no Sítio do Seu Custódio.',
    objectives: [{ key: 'abobora', need: 5, label: 'Abóboras Fujonas capturadas' }],
    progress: 'Ainda não trouxe as abóboras? Minha cabeça vai girar! ...De novo.',
    complete: 'Magnífico! Esplêndido! Horripilante! Quer dizer... horripilantemente esplêndido!\n\nComo agradecimento oficial da Prefeitura, aceite este chapéu. É de abóbora. Claro que é de abóbora.',
    rewards: { xp: 400, money: 5000, items: ['chapeu'] },
    area: 'abobora',
  },
  {
    id: 'ossos',
    title: 'Ossos do Ofício',
    level: 2,
    giver: 'juvenal',
    turnIn: 'juvenal',
    text:
      'Ô, meu chapa! Não repara a bagunça.\n\nOntem teve baile no cemitério e eu dancei tanto que me desmontei todinho! Perdi uns ossos por aí: um fêmur, umas costelas, a rótula, o dedão do pé...\n\nDá uma força e junta pra mim? Sem eles eu não consigo nem sambar direito. Só rebolar.',
    summary: 'Encontre 6 Ossos do Juvenal espalhados pelo Cemitério Sorridente.',
    objectives: [{ key: 'osso', need: 6, label: 'Ossos do Juvenal' }],
    progress: 'E aí, achou meus ossinhos? Tô me equilibrando numa perna só, parceiro.',
    complete: 'Opa! Agora sim, tô inteiraço!\n\nOlha só: quando o relógio bate a uma... TUMBALACATUMBA TUMBA TÁ! Pode ficar com a rótula que sobrou, eu tenho três.',
    rewards: { xp: 450, money: 4000, items: ['rotula'] },
    area: 'ossos',
  },
  {
    id: 'vagalumes',
    title: 'Luz Para os Defuntos',
    level: 3,
    minLevel: 2,
    giver: 'tonico',
    turnIn: 'tonico',
    night: true,
    text:
      'Minha lanterna apagou e eu tô sem querosene desde 1887. Os defuntos reclamam que não conseguem ler à noite.\n\nVaga-lume funciona bem, mas eles só saem à noite, lá no Bosque Retorcido.\n\nCaça uns 8 pra mim? E cuidado: alguns pontinhos brilhando no escuro são olhos. Esses não coloca na lanterna.',
    summary: 'Capture 8 vaga-lumes no Bosque Retorcido. Eles só aparecem à noite.',
    objectives: [{ key: 'vagalume', need: 8, label: 'Vaga-lumes capturados' }],
    progress: 'Nada ainda? Se tiver de dia, é só esperar escurecer. Eu posso te fazer companhia. Eu e os defuntos.',
    complete: 'Olha que beleza! Minha lanterna nunca brilhou tanto. Os defuntos vão poder ler as notícias do obituário... deles mesmos.\n\nToma, fiz uma lanterninha igual pra você.',
    rewards: { xp: 450, money: 4500, items: ['lanterna'] },
    area: 'vagalumes',
  },
  {
    id: 'brasas',
    title: 'O Ovo do Capeta',
    level: 2,
    giver: 'custodio',
    turnIn: 'custodio',
    text:
      'Ô, forasteiro! Cê num vai acreditá.\n\nMinha avestruz, a Dona Belinha, botô um ovo e fugiu com um bode. E o ovo é de avestruz DEMÔNIO, sabe? Vermelho, quentinho, com chifrinho.\n\nSe esfriar, choca um pintinho mal-humorado que bota fogo no celeiro. Se esquentar, choca um pintinho bem-humorado que bota fogo no celeiro devagar. Preciso de 5 Brasas Infernais das Fendas Sulfurosas pra manter o ninho quentinho.',
    summary: 'Recolha 5 Brasas Infernais nas Fendas Sulfurosas e leve para Seu Custódio.',
    objectives: [{ key: 'brasa', need: 5, label: 'Brasas Infernais' }],
    progress: 'O ovo tá esfriando, sô! Tô vendo ele fazer biquinho.',
    complete: 'Óia só que brasa bonita! Vou botá nos braseiros em volta do ninho.\n\nAgora vem a parte difícil...',
    rewards: { xp: 300, money: 3000, items: [] },
    area: 'brasas',
  },
  {
    id: 'chocar',
    title: 'Chocando o Problema',
    level: 3,
    giver: 'custodio',
    turnIn: 'custodio',
    requires: ['brasas'],
    text:
      'O ninho tá quente, mas o ovo precisa de... carinho. Calor humano. Ou quase humano, no seu caso.\n\nAlguém tem que sentar nele. Eu sentaria, mas minha ciática não deixa, e da última vez eu fiquei com o traseiro chamuscado por uma semana.\n\nVai lá atrás da casa e senta no ovo. Com jeitinho.',
    summary: 'Sente no Ovo do Capeta, no ninho atrás da casa da fazenda, até ele chocar.',
    objectives: [{ key: 'ovo', need: 1, label: 'Ovo chocado' }],
    progress: 'Já chocô? Não? Tem que sentá e ficá quietinho, uai.',
    complete: 'Ele nasceu! E já gosta de você! Olha como ele te segue... ele acha que cê é a mãe dele.\n\nParabéns, agora cê é mãe de um capetinha. Pode ficar com ele, eu já tenho problema demais.',
    rewards: { xp: 500, money: 2000, items: ['belzebu'] },
    area: 'ovo',
  },
  {
    id: 'corvos',
    title: 'Insônia de Palha',
    level: 2,
    giver: 'zepalha',
    turnIn: 'zepalha',
    text:
      'Psiu... ei... aqui em cima. É, o espantalho falante.\n\nTem uns corvos aqui que ficam rindo de mim a noite inteira. "Crá crá crá, olha o espantalho que não espanta". Eu não durmo há três colheitas!\n\nVocê parece assustador o bastante... com essa cara. Chegue perto deles e use seu melhor "BUU!" (tecla 1). Espante 6 corvos.',
    summary: 'Use "Buu!" (tecla 1) perto dos corvos do sítio para espantar 6 deles.',
    objectives: [{ key: 'corvo', need: 6, label: 'Corvos espantados' }],
    progress: 'Ainda ouço "crá crá"... isso é tortura psicológica, sabia?',
    complete: 'Silêncio... finalmente... zzz...\n\nAh! Desculpe, cochilei. Obrigado! Toma, achei isso no meu bolso de palha.',
    rewards: { xp: 350, money: 3500, items: ['pena'] },
    area: 'corvos',
  },
  {
    id: 'dentadura',
    title: 'Sorriso Perdido',
    level: 3,
    minLevel: 2,
    giver: 'conde',
    turnIn: 'conde',
    text:
      'Boa noite. Eu sou o Conde Dentúcio. E tenho um problema... delicado.\n\nDurante meu passeio noturno pelo pântano, eu espirrei. E minha dentadura voou. Ela é de ouro, com presas de marfim, e custou uma fortuna em 1703.\n\nSem ela, só consigo tomar sangue de canudinho. É humilhante. Encontre-a no Pântano dos Sapos Tristes.',
    summary: 'Recupere a dentadura do Conde no Pântano dos Sapos Tristes.',
    objectives: [{ key: 'dentadura', need: 1, label: 'Dentadura recuperada' }],
    progress: 'Ainda nada? Estou tomando sopa há três noites. Sopa. Eu. Um conde.',
    complete: 'MINHA DENTADURA!\n\n...Um sapo estava usando? E ele parecia FELIZ? Hmm. Vou fervê-la por uns duzentos anos.\n\nObrigado, mortal. Tome este colar, eu tinha um par de presas sobrando.',
    rewards: { xp: 450, money: 10000, items: ['colar'] },
    area: 'dentadura',
  },
  {
    id: 'cogumelos',
    title: 'Cogumelos Risonhos',
    level: 4,
    minLevel: 2,
    giver: 'vesga',
    turnIn: 'vesga',
    text:
      'Hihihi! Chegue mais perto, docinho. Não, não tão perto!\n\nEstou preparando minha famosa Poção do Riso Eterno, mas faltam 7 Cogumelos Risonhos. Eles crescem aqui no pântano e brilham no escuro, cor-de-rosa.\n\nSe ouvir risadinhas vindas do chão, não se assuste, são eles. Se ouvir risadinhas vindas de trás de você... aí pode se assustar.',
    summary: 'Colha 7 Cogumelos Risonhos no Pântano dos Sapos Tristes.',
    objectives: [{ key: 'cogumelo', need: 7, label: 'Cogumelos Risonhos' }],
    progress: 'Hihi... hihihi... desculpe, cheirei a poção antes da hora. Cadê meus cogumelos?',
    complete: 'Perfeito! Agora é só mexer, mexer e... HIHIHIHI!\n\nComo pagamento, leve minha vassoura velha. Ela é temperamental, mas voa baixinho. Aperte 5 para montar.',
    rewards: { xp: 500, money: 6000, items: ['vassoura'] },
    area: 'cogumelos',
  },
  {
    id: 'carta',
    title: 'Correio do Além',
    level: 1,
    giver: 'suspiro',
    turnIn: 'nevoa',
    text:
      'Ahhh... (suspiro)...\n\nHá trezentos anos eu amo a Lady Névoa, que vive no coreto da ilha do lago. Mas eu sou tímido. E transparente.\n\nEscrevi esta carta de amor com minhas próprias lágrimas de ectoplasma. Você entregaria para ela? A ponte fica do lado leste do lago.',
    summary: 'Entregue a Carta Perfumada à Lady Névoa, no coreto da ilha do Lago Lamentoso.',
    objectives: [{ key: 'carta', need: 1, label: 'Carta entregue à Lady Névoa' }],
    progress: '...',
    complete: 'Uma carta... do Suspiro? Aquele fantasminha que fica me olhando do píer há três séculos?\n\n...Que fofo. E que ortografia horrível.',
    rewards: { xp: 300, money: 1500, items: [] },
    startItem: 'carta',
    area: null,
  },
  {
    id: 'resposta',
    title: 'Resposta do Além',
    level: 2,
    giver: 'nevoa',
    turnIn: 'suspiro',
    requires: ['carta'],
    text:
      'Diga a ele que sim. SIM! Mas que ele pare de suspirar tão alto, dá para ouvir daqui da ilha.\n\nLeve este bilhete para ele. E diga que eu adoro homens transparentes. A gente vê que são sinceros.',
    summary: 'Leve o bilhete da Lady Névoa para o Suspiro, no píer do lago.',
    objectives: [{ key: 'resposta', need: 1, label: 'Bilhete entregue ao Suspiro' }],
    progress: '...',
    complete: 'ELA DISSE SIM?!\n\nAhhhhhh! Estou tão feliz que poderia morrer! ...De novo!\n\nObrigado, amigo vivo. Vou suspirar de alegria agora. BEM BAIXINHO.',
    rewards: { xp: 400, money: 5000, items: [] },
    startItem: 'resposta',
    area: null,
  },
  // ---------------------------------------------------------------- continuações
  {
    id: 'cuspe',
    title: 'Cuspe de Fogo',
    level: 3,
    minLevel: 3,
    giver: 'custodio',
    turnIn: 'custodio',
    requires: ['chocar'],
    text:
      'Ô, mãe de capetinha! Tenho uma notícia boa e uma ruim.\n\nA boa: o Belzebuzinho tá crescendo forte. A ruim: ele ainda não sabe cuspir fogo, e filhote de avestruz demônio que não cospe fogo sofre bullying no galinheiro.\n\nA vó dele só cuspia fogo depois de comer Pimenta do Capeta, que nasce lá nas Fendas Sulfurosas, pertinho das rachaduras quentes. Traz umas 5 que eu preparo um mingau ardido pro bichinho.',
    summary: 'Colha 5 Pimentas do Capeta nas Fendas Sulfurosas e leve para Seu Custódio.',
    objectives: [{ key: 'pimenta', need: 5, label: 'Pimentas do Capeta' }],
    progress: 'Cadê as pimenta? O Belzebuzinho já tentou cuspir fogo e saiu só um soluço.',
    complete: 'Óia que pimenta bonita! Arde só de olhar.\n\n(Seu Custódio mistura tudo num mingau. Belzebuzinho come, fica vermelho... mais vermelho... e solta um PUF! de fogo.)\n\nPronto! Agora ele cospe bola de fogo nos bicho que mexer com você. É fraquinho ainda, mas é de coração.',
    rewards: { xp: 450, money: 3000, items: [] },
    area: 'pimenta',
  },
  {
    id: 'baile',
    title: 'Baile de Arromba',
    level: 3,
    minLevel: 3,
    giver: 'juvenal',
    turnIn: 'juvenal',
    requires: ['ossos'],
    text:
      'Parceiro! Agora que tô inteiraço, vou dar o maior baile que esse cemitério já viu.\n\nSó tem um probleminha: umas Caveiras Saltitantes fugiram do ossário e ficam pulando nos convidados, mordendo o tornozelo de todo mundo. Assim ninguém dança!\n\nDá um jeito em 6 delas? Com a sua lanterna, de preferência. Elas são ocas, faz um barulho ótimo.',
    summary: 'Derrote 6 Caveiras Saltitantes no Cemitério Sorridente.',
    objectives: [{ key: 'caveira', need: 6, label: 'Caveiras Saltitantes derrotadas' }],
    progress: 'Ainda tem caveira mordendo canela por aí, parceiro. E eu nem tenho canela sobrando.',
    complete: 'Ouviu esse silêncio? É o som de um baile sem mordida!\n\nTumbalacatumba tumba tá! Toma essas castanholas, fiz com duas costelas minhas. Não se preocupa, eu tenho um monte.',
    rewards: { xp: 500, money: 4500, items: ['castanholas'] },
    area: 'baile',
  },
  {
    id: 'pelo',
    title: 'Poção Cabeluda',
    level: 4,
    minLevel: 4,
    giver: 'vesga',
    turnIn: 'vesga',
    requires: ['cogumelos'],
    text:
      'Hihihi! A Poção do Riso Eterno deu certo! Até demais: o Zé Palha ri dormindo e os sapos não param de gargalhar.\n\nAgora vou fazer minha obra-prima: o Tônico Capilar da Vesga! Preciso de 4 Tufos de Pelo de Aranha Cabeluda. As aranhas vivem no Bosque Retorcido e não emprestam o pelo de bom grado.\n\nConvença-as. Com força. Hihihi!',
    summary: 'Arranque 4 Tufos de Pelo das Aranhas Cabeludas do Bosque Retorcido.',
    objectives: [{ key: 'pelo', need: 4, label: 'Tufos de Pelo de Aranha' }],
    progress: 'Nada de pelo ainda? Se quiser, faço uma poção para dar coragem. Ela também dá bigode.',
    complete: 'Que tufos lindos! Macios, fedidos e com uma perninha ainda se mexendo. Perfeito!\n\n(O caldeirão borbulha e solta uma fumaça em forma de peruca.)\n\nToma um frasco. Passa na careca ou bebe, tanto faz: cura machucado e arrepia a nuca. E ele se enche sozinho, hihihi.',
    rewards: { xp: 600, money: 6500, items: ['tonico'] },
    area: 'pelo',
  },
  {
    id: 'sotao',
    title: 'Despejo no Sótão',
    level: 5,
    minLevel: 5,
    giver: 'conde',
    turnIn: 'conde',
    requires: ['dentadura'],
    text:
      'Ah, meu salvador dentário. Finalmente posso sorrir de novo... e foi sorrindo que descobri o problema.\n\nEnquanto eu estava banguela, ninguém me levava a sério. Nem os morcegos. Uns Morcegos Dentuços invadiram o sótão da mansão e agora dão festas todas as noites. Com o MEU sangue de reserva!\n\nExpulse 5 deles. Eu mesmo faria, mas acabei de fazer as unhas.',
    summary: 'Derrote 5 Morcegos Dentuços em volta da Mansão Dentúcio.',
    objectives: [{ key: 'morcego', need: 5, label: 'Morcegos Dentuços expulsos' }],
    progress: 'Ainda ouço guinchos no sótão. E alguém toca órgão de madrugada. Não sou eu.',
    complete: 'Silêncio no sótão! Que maravilha. Dá até para ouvir os fantasmas do porão reclamando, como nos velhos tempos.\n\nPegue esta capa. Era do meu tataravô. Está um pouco roída, mas continua dramática.',
    rewards: { xp: 700, money: 12000, items: ['capa'] },
    area: 'sotao',
  },
  {
    id: 'casamento',
    title: 'Casamento no Farol',
    level: 5,
    minLevel: 5,
    giver: 'suspiro',
    turnIn: 'nevoa',
    requires: ['resposta'],
    text:
      'Ahhh... (suspiro de felicidade)... Vamos nos casar! Eu e a Lady Névoa! No Farol Desalinhado, à luz do farol, como nos romances de mil setecentos e pouco.\n\nSó que o farol está apagado há cem anos. E uns Marujos Afogados tomaram conta do penhasco: pingam no tapete e cantam desafinado.\n\nDerrote 4 marujos, suba e acenda o lampião do farol. Depois avise minha noiva na ilha. Eu faria isso, mas sou transparente e eles não me levam a sério.',
    summary: 'Derrote 4 Marujos Afogados, acenda o lampião do Farol Desalinhado e avise a Lady Névoa.',
    objectives: [{ key: 'marujo', need: 4, label: 'Marujos Afogados derrotados' }, { key: 'farol', need: 1, label: 'Lampião do farol aceso' }],
    progress: 'O Suspiro me contou do casamento. Não piso naquele farol enquanto estiver escuro e cheio de marinheiro molhado.',
    complete: 'O farol... está aceso? Depois de cem anos?\n\n(Lady Névoa enxuga uma lágrima de ectoplasma.)\n\nDiga ao Suspiro que aceito. De novo. E que ele pode parar de suspirar, agora é oficial. Fique com o meu buquê. Quem pega o buquê é o próximo a... bem, a morrer de amor.',
    rewards: { xp: 750, money: 15000, items: ['buque'] },
    area: 'casamento',
  },
];

// XP necessária para passar de cada nível
export const XP_TABLE = [0, 500, 800, 1100, 1400, 1700, 2100, 2600];

export const NPC_INFO = {
  prefeito: {
    name: 'Prefeito Abóbora', title: 'Prefeito Reeleito (por pouco)', level: 12,
    greet: 'Bem-vindo à Vila Tumbalacatumba! População: 312 almas. Algumas ainda vivas.',
    barks: ['Votem em mim! Ou eu assombro vocês!', 'Minha cabeça está girando... literalmente.', 'Festival da Colheita Macabra: este ano, com MENOS incêndios!', 'Alguém viu minhas abóboras?'],
    gossip: [{ text: 'Por que sua cabeça gira?', reply: 'É um mecanismo de defesa política. Um lado para as promessas, o outro para as desculpas.' }],
  },
  aranhilda: {
    name: 'Dona Aranhilda', title: 'Vizinha Preocupada', level: 8,
    greet: 'Você viu um gato de três olhos? Não? Então por que está parado aí? Pode entrar, as aranhas não mordem. Muito.',
    barks: ['Bigodes! Psss psss psss!', 'Minhas aranhas precisam de um corte de cabelo.', 'Na minha época, os fantasmas tinham educação.'],
  },
  juvenal: {
    name: 'Juvenal', title: 'Esqueleto Festeiro', level: 6,
    greet: 'E aí, parceiro? Tô meio desmontado hoje.',
    greetDone: 'Tumbalacatumba tumba tá! Quer dançar? Aperta o 2!',
    barks: ['Alguém viu minha rótula?', 'Tumbalacatumba tumba tá!', 'Eu já fui o rei do baile. Em 1920.', 'Tô com frio nos ossos. Literalmente.'],
  },
  tonico: {
    name: 'Coveiro Tonico', title: 'Zelador do Cemitério', level: 9,
    greet: 'Cova nova, cova velha, tudo é cova. Precisa de alguma coisa, vivente?',
    barks: ['Mais um dia, mais uma cova.', 'Os defuntos estão reclamando do barulho de novo.', 'Não pisa na grama, tem gente dormindo.'],
    gossip: [{ text: 'Posso esperar anoitecer aqui com você?', action: 'sleep', nightOnly: false }],
  },
  custodio: {
    name: 'Seu Custódio', title: 'Fazendeiro Remendado', level: 7,
    greet: 'Ô de casa! Cuidado onde pisa, as abóboras mordem.',
    barks: ['Esse ovo tá me olhando torto...', 'Remendei meu braço com linha de pesca. Ficou ótimo.', 'Chuva de sapo amanhã, dizem.'],
  },
  zepalha: {
    name: 'Zé Palha', title: 'Espantalho Insone', level: 4,
    greet: 'Psiu. É, eu falo. Não conta pros corvos.',
    barks: ['Crá crá é a mãe!', 'Zzz... ah, não, eles voltaram.', 'Eu era pra espantar, não ser espantado.'],
  },
  conde: {
    name: 'Conde Dentúcio', title: 'Nobre Banguela', level: 15,
    greet: 'Boa noite. Todas as noites são boas noites. Principalmente as de lua cheia.',
    barks: ['Hmpf. Sopa de novo.', 'Ninguém respeita um vampiro banguela.', 'Eu era temido! Temido, ouviu?'],
  },
  vesga: {
    name: 'Madame Vesga', title: 'Bruxa do Pântano', level: 11,
    greet: 'Hihihi! Você é de verdade ou é uma das minhas alucinações?',
    barks: ['Olho de sapo, perna de... ah, acabou a perna.', 'Hihihi!', 'Quem mexeu no meu caldeirão?!'],
  },
  suspiro: {
    name: 'Suspiro', title: 'Fantasma Apaixonado', level: 5,
    greet: 'Ahhh... (suspiro)... ela é tão linda... e tão longe...',
    barks: ['Ahhhh...', 'Ela nem sabe que eu existo... e eu mal existo.', '(suspiro profundo)'],
  },
  nevoa: {
    name: 'Lady Névoa', title: 'Noiva da Ilha', level: 10,
    greet: 'Quem ousa perturbar meu luto eterno? Ah, é só um vivo.',
    barks: ['Estou de luto há 300 anos. Por mim mesma.', 'Alguém tem uma flor que não esteja murcha?'],
  },
};

export const ZONE_FLAVOR = {
  praca: '(Território Festivo)',
  vila: '(Território Levemente Assombrado)',
  cemiterio: '(Território Sagrado... e Barulhento)',
  lago: '(Território Úmido)',
  colina: '(Território Espiralado)',
  pantano: '(Território Coaxante)',
  bosque: '(Território Hostil a Lenhadores)',
  sitio: '(Território Rural)',
  fendas: '(Território Quente)',
  mansao: '(Propriedade Privada — Visitas só à noite)',
  farol: '(Território Inclinado)',
};

export const TIPS = [
  'Dica: Segure o botão direito do mouse para girar a câmera e o personagem ao mesmo tempo.',
  'Dica: Clique com o botão direito em um personagem para conversar.',
  'Dica: Um ! cor de abóbora indica uma missão disponível. Um ? cor de abóbora indica uma missão pronta para entregar.',
  'Dica: Pressione M para abrir o mapa e L para abrir o Diário de Missões.',
  'Dica: Pressione R para correr automaticamente.',
  'Dica: A Lápide de Regresso (tecla 6) leva você de volta à praça.',
  'Dica: Vaga-lumes só aparecem à noite. O Coveiro Tonico pode ajudar você a esperar.',
  'Dica: Terminou uma missão? Volte a quem pediu: muita história tem continuação.',
];
