/**
 * Tabelas numéricas do Livro do Jogador D&D 3ª edição (3.0) usadas pela ficha.
 * Transcritas da pesquisa registrada em TASKS/TASK_003.md (fontes: SRD 3.0,
 * dados 3e do PCGen, SRD 3.0 do dragon.ee, D&D 3.5 Update Booklet). Ao corrigir
 * um valor, cite a fonte na TASK_003 e ajuste o teste de regras correspondente.
 * Chaves de classe: bar, bad, cle, dru, gue, mon, pal, ran, lad, fei, mag.
 * Magias: linha = nível de classe 1..20; coluna = nível de magia 0..9;
 * null = não pode lançar esse nível; 0 = só com magias adicionais por atributo.
 */
export const T30 = {
  pontosPericia: {"bar":4,"bad":4,"cle":2,"dru":4,"gue":2,"mon":4,"pal":2,"ran":4,"lad":8,"fei":2,"mag":2},
  dadoVida: {"bar":12,"bad":6,"cle":8,"dru":8,"gue":10,"mon":8,"pal":10,"ran":10,"lad":6,"fei":4,"mag":4},
  salvamentosBons: {"bar":["fort"],"bad":["ref","von"],"cle":["fort","von"],"dru":["fort","von"],"gue":["fort"],"mon":["fort","ref","von"],"pal":["fort"],"ran":["fort"],"lad":["ref"],"fei":["von"],"mag":["von"]},
  bbaPorClasse: {"bar":"bom","bad":"medio","cle":"medio","dru":"medio","gue":"bom","mon":"medio","pal":"bom","ran":"bom","lad":"medio","fei":"ruim","mag":"ruim"},
  atributoConjuracao: {"bad":"CAR","cle":"SAB","dru":"SAB","pal":"SAB","ran":"SAB","fei":"CAR","mag":"INT"},
  magiasPorDia: {
    bad: [
      [2,null,null,null,null,null,null,null,null,null],
      [3,0,null,null,null,null,null,null,null,null],
      [3,1,null,null,null,null,null,null,null,null],
      [3,2,0,null,null,null,null,null,null,null],
      [3,3,1,null,null,null,null,null,null,null],
      [3,3,2,null,null,null,null,null,null,null],
      [3,3,2,0,null,null,null,null,null,null],
      [3,3,3,1,null,null,null,null,null,null],
      [3,3,3,2,null,null,null,null,null,null],
      [3,3,3,2,0,null,null,null,null,null],
      [3,3,3,3,1,null,null,null,null,null],
      [3,3,3,3,2,null,null,null,null,null],
      [3,3,3,3,2,0,null,null,null,null],
      [4,3,3,3,3,1,null,null,null,null],
      [4,4,3,3,3,2,null,null,null,null],
      [4,4,4,3,3,2,0,null,null,null],
      [4,4,4,4,3,3,1,null,null,null],
      [4,4,4,4,4,3,2,null,null,null],
      [4,4,4,4,4,4,3,null,null,null],
      [4,4,4,4,4,4,4,null,null,null],
    ],
    cle: [
      [3,1,null,null,null,null,null,null,null,null],
      [4,2,null,null,null,null,null,null,null,null],
      [4,2,1,null,null,null,null,null,null,null],
      [5,3,2,null,null,null,null,null,null,null],
      [5,3,2,1,null,null,null,null,null,null],
      [5,3,3,2,null,null,null,null,null,null],
      [6,4,3,2,1,null,null,null,null,null],
      [6,4,3,3,2,null,null,null,null,null],
      [6,4,4,3,2,1,null,null,null,null],
      [6,4,4,3,3,2,null,null,null,null],
      [6,5,4,4,3,2,1,null,null,null],
      [6,5,4,4,3,3,2,null,null,null],
      [6,5,5,4,4,3,2,1,null,null],
      [6,5,5,4,4,3,3,2,null,null],
      [6,5,5,5,4,4,3,2,1,null],
      [6,5,5,5,4,4,3,3,2,null],
      [6,5,5,5,5,4,4,3,2,1],
      [6,5,5,5,5,4,4,3,3,2],
      [6,5,5,5,5,5,4,4,3,3],
      [6,5,5,5,5,5,4,4,4,4],
    ],
    dru: [
      [3,1,null,null,null,null,null,null,null,null],
      [4,2,null,null,null,null,null,null,null,null],
      [4,2,1,null,null,null,null,null,null,null],
      [5,3,2,null,null,null,null,null,null,null],
      [5,3,2,1,null,null,null,null,null,null],
      [5,3,3,2,null,null,null,null,null,null],
      [6,4,3,2,1,null,null,null,null,null],
      [6,4,3,3,2,null,null,null,null,null],
      [6,4,4,3,2,1,null,null,null,null],
      [6,4,4,3,3,2,null,null,null,null],
      [6,5,4,4,3,2,1,null,null,null],
      [6,5,4,4,3,3,2,null,null,null],
      [6,5,5,4,4,3,2,1,null,null],
      [6,5,5,4,4,3,3,2,null,null],
      [6,5,5,5,4,4,3,2,1,null],
      [6,5,5,5,4,4,3,3,2,null],
      [6,5,5,5,5,4,4,3,2,1],
      [6,5,5,5,5,4,4,3,3,2],
      [6,5,5,5,5,5,4,4,3,3],
      [6,5,5,5,5,5,4,4,4,4],
    ],
    pal: [
      [null,null,null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null,null,null],
      [null,0,null,null,null,null,null,null,null,null],
      [null,0,null,null,null,null,null,null,null,null],
      [null,1,null,null,null,null,null,null,null,null],
      [null,1,null,null,null,null,null,null,null,null],
      [null,1,0,null,null,null,null,null,null,null],
      [null,1,0,null,null,null,null,null,null,null],
      [null,1,1,null,null,null,null,null,null,null],
      [null,1,1,0,null,null,null,null,null,null],
      [null,1,1,1,null,null,null,null,null,null],
      [null,1,1,1,null,null,null,null,null,null],
      [null,2,1,1,0,null,null,null,null,null],
      [null,2,1,1,1,null,null,null,null,null],
      [null,2,2,1,1,null,null,null,null,null],
      [null,2,2,2,1,null,null,null,null,null],
      [null,3,2,2,1,null,null,null,null,null],
      [null,3,3,3,2,null,null,null,null,null],
      [null,3,3,3,3,null,null,null,null,null],
    ],
    ran: [
      [null,null,null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null,null,null],
      [null,0,null,null,null,null,null,null,null,null],
      [null,0,null,null,null,null,null,null,null,null],
      [null,1,null,null,null,null,null,null,null,null],
      [null,1,null,null,null,null,null,null,null,null],
      [null,1,0,null,null,null,null,null,null,null],
      [null,1,0,null,null,null,null,null,null,null],
      [null,1,1,null,null,null,null,null,null,null],
      [null,1,1,0,null,null,null,null,null,null],
      [null,1,1,1,null,null,null,null,null,null],
      [null,1,1,1,null,null,null,null,null,null],
      [null,2,1,1,0,null,null,null,null,null],
      [null,2,1,1,1,null,null,null,null,null],
      [null,2,2,1,1,null,null,null,null,null],
      [null,2,2,2,1,null,null,null,null,null],
      [null,3,2,2,1,null,null,null,null,null],
      [null,3,3,3,2,null,null,null,null,null],
      [null,3,3,3,3,null,null,null,null,null],
    ],
    fei: [
      [5,3,null,null,null,null,null,null,null,null],
      [6,4,null,null,null,null,null,null,null,null],
      [6,5,null,null,null,null,null,null,null,null],
      [6,6,3,null,null,null,null,null,null,null],
      [6,6,4,null,null,null,null,null,null,null],
      [6,6,5,3,null,null,null,null,null,null],
      [6,6,6,4,null,null,null,null,null,null],
      [6,6,6,5,3,null,null,null,null,null],
      [6,6,6,6,4,null,null,null,null,null],
      [6,6,6,6,5,3,null,null,null,null],
      [6,6,6,6,6,4,null,null,null,null],
      [6,6,6,6,6,5,3,null,null,null],
      [6,6,6,6,6,6,4,null,null,null],
      [6,6,6,6,6,6,5,3,null,null],
      [6,6,6,6,6,6,6,4,null,null],
      [6,6,6,6,6,6,6,5,3,null],
      [6,6,6,6,6,6,6,6,4,null],
      [6,6,6,6,6,6,6,6,5,3],
      [6,6,6,6,6,6,6,6,6,4],
      [6,6,6,6,6,6,6,6,6,6],
    ],
    mag: [
      [3,1,null,null,null,null,null,null,null,null],
      [4,2,null,null,null,null,null,null,null,null],
      [4,2,1,null,null,null,null,null,null,null],
      [4,3,2,null,null,null,null,null,null,null],
      [4,3,2,1,null,null,null,null,null,null],
      [4,3,3,2,null,null,null,null,null,null],
      [4,4,3,2,1,null,null,null,null,null],
      [4,4,3,3,2,null,null,null,null,null],
      [4,4,4,3,2,1,null,null,null,null],
      [4,4,4,3,3,2,null,null,null,null],
      [4,4,4,4,3,2,1,null,null,null],
      [4,4,4,4,3,3,2,null,null,null],
      [4,4,4,4,4,3,2,1,null,null],
      [4,4,4,4,4,3,3,2,null,null],
      [4,4,4,4,4,4,3,2,1,null],
      [4,4,4,4,4,4,3,3,2,null],
      [4,4,4,4,4,4,4,3,2,1],
      [4,4,4,4,4,4,4,3,3,2],
      [4,4,4,4,4,4,4,4,3,3],
      [4,4,4,4,4,4,4,4,4,4],
    ],
  },
  magiasConhecidas: {
    bad: [
      [4,null,null,null,null,null,null,null,null,null],
      [5,2,null,null,null,null,null,null,null,null],
      [6,3,null,null,null,null,null,null,null,null],
      [6,3,2,null,null,null,null,null,null,null],
      [6,4,3,null,null,null,null,null,null,null],
      [6,4,3,null,null,null,null,null,null,null],
      [6,4,4,2,null,null,null,null,null,null],
      [6,4,4,3,null,null,null,null,null,null],
      [6,4,4,3,null,null,null,null,null,null],
      [6,4,4,4,2,null,null,null,null,null],
      [6,4,4,4,3,null,null,null,null,null],
      [6,4,4,4,3,null,null,null,null,null],
      [6,4,4,4,4,2,null,null,null,null],
      [6,4,4,4,4,3,null,null,null,null],
      [6,4,4,4,4,3,null,null,null,null],
      [6,5,4,4,4,4,2,null,null,null],
      [6,5,5,4,4,4,3,null,null,null],
      [6,5,5,5,4,4,3,null,null,null],
      [6,5,5,5,5,4,4,null,null,null],
      [6,5,5,5,5,5,4,null,null,null],
    ],
    fei: [
      [4,2,null,null,null,null,null,null,null,null],
      [5,2,null,null,null,null,null,null,null,null],
      [5,3,null,null,null,null,null,null,null,null],
      [6,3,1,null,null,null,null,null,null,null],
      [6,4,2,null,null,null,null,null,null,null],
      [7,4,2,1,null,null,null,null,null,null],
      [7,5,3,2,null,null,null,null,null,null],
      [8,5,3,2,1,null,null,null,null,null],
      [8,5,4,3,2,null,null,null,null,null],
      [9,5,4,3,2,1,null,null,null,null],
      [9,5,5,4,3,2,null,null,null,null],
      [9,5,5,4,3,2,1,null,null,null],
      [9,5,5,4,4,3,2,null,null,null],
      [9,5,5,4,4,3,2,1,null,null],
      [9,5,5,4,4,4,3,2,null,null],
      [9,5,5,4,4,4,3,2,1,null],
      [9,5,5,4,4,4,3,3,2,null],
      [9,5,5,4,4,4,3,3,2,1],
      [9,5,5,4,4,4,3,3,3,2],
      [9,5,5,4,4,4,3,3,3,3],
    ],
  },
  xpPorNivel: [0,1000,3000,6000,10000,15000,21000,28000,36000,45000,55000,66000,78000,91000,105000,120000,136000,153000,171000,190000],
  /** Capacidade de carga (limite superior de leve / média / pesada, em libras), For 1–29; acima de 29, ×4 a cada 10 pontos. */
  capacidadeCargaLb: {
    1: [3,6,10],
    2: [6,13,20],
    3: [10,20,30],
    4: [13,26,40],
    5: [16,33,50],
    6: [20,40,60],
    7: [23,46,70],
    8: [26,53,80],
    9: [30,60,90],
    10: [33,66,100],
    11: [38,76,115],
    12: [43,86,130],
    13: [50,100,150],
    14: [58,116,175],
    15: [66,133,200],
    16: [76,153,230],
    17: [86,173,260],
    18: [100,200,300],
    19: [116,233,350],
    20: [133,266,400],
    21: [153,306,460],
    22: [173,346,520],
    23: [200,400,600],
    24: [233,466,700],
    25: [266,533,800],
    26: [306,613,920],
    27: [346,693,1040],
    28: [400,800,1200],
    29: [466,933,1400],
  },
  /** A edição brasileira converte 1 libra ≈ 0,5 kg (30 pés = 9 m). */
  kgPorLibra: 0.5,
  tamanho: {
    minimo: { ca: 8, ataque: 8, esconder: 16, carga: 1 / 8 },
    minusculo: { ca: 2, ataque: 2, esconder: 8, carga: 1 / 2 },
    pequeno: { ca: 1, ataque: 1, esconder: 4, carga: 3 / 4 },
    medio: { ca: 0, ataque: 0, esconder: 0, carga: 1 },
    grande: { ca: -1, ataque: -1, esconder: -4, carga: 2 },
    enorme: { ca: -2, ataque: -2, esconder: -8, carga: 4 },
    imenso: { ca: -4, ataque: -4, esconder: -12, carga: 8 },
    colossal: { ca: -8, ataque: -8, esconder: -16, carga: 16 },
  },
  /** Monge 3.0: coluna própria de ataque desarmado, deslocamento sem armadura e bônus de CA. */
  monge: {
    ataqueDesarmado: [[0], [1], [2], [3], [3], [4, 1], [5, 2], [6, 3], [6, 3], [7, 4, 1], [8, 5, 2], [9, 6, 3], [9, 6, 3], [10, 7, 4, 1], [11, 8, 5, 2], [12, 9, 6, 3], [12, 9, 6, 3], [13, 10, 7, 4, 1], [14, 11, 8, 5, 2], [15, 12, 9, 6, 3]],
    danoDesarmado: ['1d6', '1d6', '1d6', '1d8', '1d8', '1d8', '1d8', '1d10', '1d10', '1d10', '1d10', '1d12', '1d12', '1d12', '1d12', '1d20', '1d20', '1d20', '1d20', '1d20'],
    deslocamento: [9, 9, 12, 12, 12, 15, 15, 15, 18, 18, 18, 21, 21, 21, 24, 24, 24, 27, 27, 27],
    /** SRD 3.0, tabela "Small Monk Unarmed Damage and Small Monk & Dwarf Monk Speed" (pés → m: 5 pés = 1,5 m). */
    danoDesarmadoPequeno: ['1d4', '1d4', '1d4', '1d6', '1d6', '1d6', '1d6', '1d8', '1d8', '1d8', '1d8', '1d10', '1d10', '1d10', '1d10', '2d6', '2d6', '2d6', '2d6', '2d6'],
    deslocamentoPequeno: [6, 6, 7.5, 7.5, 7.5, 10.5, 10.5, 10.5, 12, 12, 12, 13.5, 13.5, 13.5, 16.5, 16.5, 16.5, 18, 18, 18],
  },
  /** Perícias de classe da 3.0 (SRD 3.0, "Class Skills"), com os nomes do compêndio sem acento.
   *  Equivalências 3.0 → compêndio (3.5): Pick Pocket → Prestidigitação; Tumble → Acrobacias;
   *  Wilderness Lore e Intuit Direction → Sobrevivência; Disable Device → Operar Mecanismo.
   *  Alquimia, Empatia com Animais, Mensagens Secretas, Ler Lábios e Vidência não existem no compêndio.
   *  "conhecimento (*)" = todos os Conhecimentos. */
  periciasClasse: {
    bar: ['escalar', 'oficios', 'adestrar animais', 'intimidacao', 'saltar', 'ouvir', 'cavalgar', 'natacao', 'sobrevivencia'],
    bad: ['avaliacao', 'equilibrio', 'blefar', 'escalar', 'concentracao', 'oficios', 'decifrar escrita', 'diplomacia', 'disfarces', 'arte da fuga', 'obter informacao', 'esconder-se', 'saltar', 'conhecimento (*)', 'ouvir', 'furtividade', 'atuacao', 'prestidigitacao', 'profissao', 'sentir motivacao', 'falar idioma', 'identificar magia', 'natacao', 'acrobacias', 'usar instrumento magico', 'sobrevivencia'],
    cle: ['concentracao', 'oficios', 'diplomacia', 'cura', 'conhecimento (arcano)', 'conhecimento (religiao)', 'profissao', 'identificar magia'],
    dru: ['concentracao', 'oficios', 'diplomacia', 'adestrar animais', 'cura', 'conhecimento (natureza)', 'profissao', 'identificar magia', 'natacao', 'sobrevivencia'],
    gue: ['escalar', 'oficios', 'adestrar animais', 'saltar', 'cavalgar', 'natacao'],
    mon: ['equilibrio', 'escalar', 'concentracao', 'oficios', 'diplomacia', 'arte da fuga', 'esconder-se', 'saltar', 'conhecimento (arcano)', 'ouvir', 'furtividade', 'atuacao', 'profissao', 'natacao', 'acrobacias'],
    pal: ['concentracao', 'oficios', 'diplomacia', 'adestrar animais', 'cura', 'conhecimento (religiao)', 'profissao', 'cavalgar'],
    ran: ['escalar', 'concentracao', 'oficios', 'adestrar animais', 'cura', 'esconder-se', 'saltar', 'conhecimento (natureza)', 'ouvir', 'furtividade', 'profissao', 'cavalgar', 'procurar', 'observar', 'natacao', 'usar cordas', 'sobrevivencia'],
    lad: ['avaliacao', 'equilibrio', 'blefar', 'escalar', 'oficios', 'decifrar escrita', 'diplomacia', 'operar mecanismo', 'disfarces', 'arte da fuga', 'falsificacao', 'obter informacao', 'esconder-se', 'intimidacao', 'saltar', 'ouvir', 'furtividade', 'abrir fechaduras', 'atuacao', 'prestidigitacao', 'profissao', 'procurar', 'sentir motivacao', 'observar', 'natacao', 'acrobacias', 'usar instrumento magico', 'usar cordas', 'sobrevivencia'],
    fei: ['concentracao', 'oficios', 'conhecimento (arcano)', 'profissao', 'identificar magia'],
    mag: ['concentracao', 'oficios', 'conhecimento (*)', 'profissao', 'identificar magia'],
  },
  /** Perícias exclusivas (3.0): só quem as tem como perícia de classe pode comprá-las. */
  periciasExclusivas: ['decifrar escrita', 'usar instrumento magico'],
  /** Proficiências da classe (SRD 3.0, "Weapon and Armor Proficiency"), como talentos concedidos no 1º nível. */
  proficienciasClasse: {
    bar: ['Usar Arma Simples', 'Usar Arma Comum', 'Usar Armadura (leve)', 'Usar Armadura (média)', 'Usar Escudo'],
    bad: ['Usar Arma Simples', 'Usar Armadura (leve)', 'Usar Armadura (média)', 'Usar Escudo'],
    cle: ['Usar Arma Simples', 'Usar Armadura (leve)', 'Usar Armadura (média)', 'Usar Armadura (pesada)', 'Usar Escudo'],
    dru: ['Usar Armadura (leve)', 'Usar Armadura (média)', 'Usar Escudo'],
    gue: ['Usar Arma Simples', 'Usar Arma Comum', 'Usar Armadura (leve)', 'Usar Armadura (média)', 'Usar Armadura (pesada)', 'Usar Escudo'],
    mon: [],
    pal: ['Usar Arma Simples', 'Usar Arma Comum', 'Usar Armadura (leve)', 'Usar Armadura (média)', 'Usar Armadura (pesada)', 'Usar Escudo'],
    ran: ['Usar Arma Simples', 'Usar Arma Comum', 'Usar Armadura (leve)', 'Usar Armadura (média)', 'Usar Escudo'],
    lad: ['Usar Armadura (leve)'],
    fei: ['Usar Arma Simples'],
    mag: [],
  },
  /** Armas específicas (fora dos grupos simples/comuns) de cada classe, para a ficha. */
  armasClasse: {
    bad: 'armas simples + uma entre arco longo, arco longo composto, espada longa, rapieira, porrete, arco curto composto, espada curta, arco curto ou chicote',
    dru: 'clava, adaga, dardo, meia-lança, lança longa, bordão, cimitarra, foice, lança curta e funda (armaduras não metálicas; escudos de madeira)',
    mon: 'clava, besta leve ou pesada, adaga, machadinha, azagaia, kama, nunchaku, bordão, shuriken, siangham e funda',
    lad: 'besta de mão ou leve, adaga, dardo, maça leve, porrete, arco curto (normal e composto) e espada curta; Médio: também clava, besta pesada, maça pesada, maça-estrela, bordão e rapieira',
    mag: 'clava, adaga, besta leve, besta pesada e bordão',
  },
  /** Talentos que a classe concede (não ocupam vaga): [nível, talento, observação]. */
  talentosClasse: {
    mon: [[1, 'Ataque Desarmado Aprimorado', 'desarmado'], [2, 'Desviar Objetos'], [6, 'Imobilização Aprimorada']],
    ran: [[1, 'Rastrear'], [1, 'Ambidestria', 'com armadura leve ou sem armadura'], [1, 'Combater com Duas Armas', 'com armadura leve ou sem armadura']],
    mag: [[1, 'Escrever Pergaminho']],
  },
  /** Talentos que a raça concede: [talento, parâmetro]. */
  talentosRaca: {
    elfo: [['Usar Arma Comum', 'espada longa ou rapieira; arco longo e arco curto, normais e compostos']],
  },
  /** Talentos que exigem uma escolha (arma, perícia, escola de magia ou magias). */
  talentosParametro: {
    'foco em arma': 'arma',
    'especializacao em arma': 'arma',
    'acuidade com arma': 'arma',
    'sucesso decisivo aprimorado': 'arma',
    'usar arma exotica': 'arma',
    'usar arma comum': 'arma',
    'foco em pericia': 'pericia',
    'foco em magia': 'escola',
    'dominar magia': 'magias',
  },
  parametroRotulo: { arma: 'a arma', pericia: 'a perícia', escola: 'a escola de magia', magias: 'as magias' },
  /** Nomes da 3.5 usados nos requisitos do compêndio → talento 3.0 equivalente. */
  talentosApelidos: {
    'separar aprimorado': 'separar',
    'reflexos em combate': 'reflexos de combate',
  },
  /** Efeitos numéricos de talentos 3.0 que a ficha soma sozinha. */
  efeitosTalentos: {
    'iniciativa aprimorada': { iniciativa: 4 },
    'reflexos rapidos': { resistencias: { ref: 2 } },
    'fortitude maior': { resistencias: { fort: 2 } },
    'vontade de ferro': { resistencias: { von: 2 } },
    prontidao: { pericias: { ouvir: 2, observar: 2 } },
    'foco em pericia': { periciaDoParametro: 2 },
    esquiva: { condicional: '+1 de esquiva na CA contra um oponente escolhido (Esquiva)' },
    vitalidade: { pv: 3 }, // os PV são cadastrados à mão: vira nota na ficha
  },
  /** Sinergias de perícia (SRD 3.0, skills.htm): +2 com 5 graduações em qualquer perícia de `de` (não acumula). */
  sinergias: [
    { de: ['acrobacias'], para: 'equilibrio' },
    { de: ['acrobacias'], para: 'saltar' },
    { de: ['saltar'], para: 'acrobacias' },
    { de: ['blefar'], para: 'intimidacao' },
    { de: ['blefar'], para: 'prestidigitacao' },
    { de: ['blefar', 'sentir motivacao'], para: 'diplomacia' },
    { de: ['adestrar animais'], para: 'cavalgar' },
  ],
  /** Sinergias que só valem em certas situações: viram nota na ficha. */
  sinergiasSituacionais: [
    { de: 'blefar', texto: '+2 em Disfarces ao agir no papel quando observado (Blefar 5+)' },
    { de: 'usar cordas', texto: '+2 em Escalar com corda e em Arte da Fuga contra amarras de corda (Usar Cordas 5+)' },
    { de: 'decifrar escrita', texto: '+2 em Usar Instrumento Mágico com pergaminhos (Decifrar Escrita 5+)' },
    { de: 'identificar magia', texto: '+2 em Usar Instrumento Mágico com pergaminhos (Identificar Magia 5+)' },
    { de: 'usar instrumento magico', texto: '+2 em Identificar Magia para decifrar pergaminhos (Usar Instrumento Mágico 5+)' },
    { de: 'arte da fuga', texto: '+2 em Usar Cordas para amarrar alguém (Arte da Fuga 5+)' },
  ],
  /** Traços raciais que afetam números da ficha (Livro do Jogador 3.0, cap. 2; SRD 3.0).
   *  "ajustes" e "tamanho" prevalecem sobre o compêndio, que só guarda um bônus e uma penalidade.
   *  "condicionais" vão no quadro dos testes de resistência; "condicionaisCombate" (ataque/CA), nas habilidades especiais. */
  racas: {
    humano: {
      deslocamento: 9,
      tamanho: 'medio',
      ajustes: {},
      tracos: ['1 talento adicional no 1º nível', '4 pontos de perícia adicionais no 1º nível e 1 adicional por nível', 'Classe favorecida: qualquer (a de nível mais alto)'],
      idiomas: { automaticos: ['Comum'], adicionais: 'qualquer' },
    },
    anao: {
      deslocamento: 6,
      tamanho: 'medio',
      ajustes: { con: 2, car: -2 },
      tracos: ['Visão no escuro 18 m', 'Especialização em rochas: +2 em Procurar para notar trabalhos incomuns em pedra', '+2 em Avaliação e Ofícios ligados a pedra ou metal', 'Deslocamento reduzido para 4,5 m por armadura ou carga média/pesada', 'Classe favorecida: guerreiro'],
      condicionais: ['+2 contra venenos', '+2 contra magias e efeitos similares a magia'],
      condicionaisCombate: ['+1 de ataque contra orcs e goblinoides', '+4 de esquiva na CA contra gigantes'],
      idiomas: { automaticos: ['Comum', 'Anão'], adicionais: 'Gigante, Gnomo, Goblin, Orc, Terran e Subcomum' },
    },
    elfo: {
      deslocamento: 9,
      tamanho: 'medio',
      ajustes: { des: 2, con: -2 },
      pericias: { ouvir: 2, procurar: 2, observar: 2 },
      tracos: ['Imune a magias e efeitos de sono', 'Visão na penumbra', 'Procura automaticamente portas secretas ao passar a até 1,5 m', 'Classe favorecida: mago'],
      condicionais: ['+2 contra magias e efeitos de encantamento'],
      idiomas: { automaticos: ['Comum', 'Élfico'], adicionais: 'Dracônico, Gnoll, Gnomo, Goblin, Orc e Silvestre' },
    },
    gnomo: {
      deslocamento: 6,
      tamanho: 'pequeno',
      ajustes: { con: 2, for: -2 },
      pericias: { ouvir: 2 },
      tracos: ['Visão na penumbra', '+2 em Alquimia', 'Falar com animais (mamífero escavador) 1/dia; com Int 10+: globos de luz, som fantasma e prestidigitação 1/dia cada', 'Classe favorecida: mago (ilusionista)'],
      condicionais: ['+2 contra ilusões'],
      condicionaisCombate: ['+1 de ataque contra kobolds e goblinoides', '+4 de esquiva na CA contra gigantes'],
      idiomas: { automaticos: ['Comum', 'Gnomo'], adicionais: 'Dracônico, Anão, Élfico, Gigante, Goblin e Orc' },
    },
    'meio-elfo': {
      deslocamento: 9,
      tamanho: 'medio',
      ajustes: {},
      pericias: { ouvir: 1, procurar: 1, observar: 1 },
      tracos: ['Imune a magias e efeitos de sono', 'Visão na penumbra', 'Sangue élfico (conta como elfo para efeitos)', 'Classe favorecida: qualquer (a de nível mais alto)'],
      condicionais: ['+2 contra magias e efeitos de encantamento'],
      idiomas: { automaticos: ['Comum', 'Élfico'], adicionais: 'qualquer' },
    },
    'meio-orc': {
      deslocamento: 9,
      tamanho: 'medio',
      ajustes: { for: 2, int: -2, car: -2 },
      tracos: ['Visão no escuro 18 m', 'Sangue orc (conta como orc para efeitos)', 'Classe favorecida: bárbaro'],
      idiomas: { automaticos: ['Comum', 'Orc'], adicionais: 'Dracônico, Gigante, Gnoll, Goblin e Abissal' },
    },
    halfling: {
      deslocamento: 6,
      tamanho: 'pequeno',
      ajustes: { des: 2, for: -2 },
      bonusResistencias: 1,
      pericias: { escalar: 2, saltar: 2, ouvir: 2, furtividade: 2 },
      tracos: ['+1 em todos os testes de resistência (já somado)', 'Classe favorecida: ladino'],
      condicionais: ['+2 de moral contra medo'],
      condicionaisCombate: ['+1 de ataque com armas de arremesso'],
      idiomas: { automaticos: ['Comum', 'Halfling'], adicionais: 'Anão, Élfico, Gnomo, Goblin e Orc' },
    },
  },
};
